# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-21 08:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminder', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reminder',
            name='warning_event',
            field=models.IntegerField(choices=[(0, 'Always'), (1, 'Raining tomorrow'), (2, 'Snowing tomorrow'), (3, 'Temperature dropping by 5F tomorrow'), (4, 'Temperature rising by 5F tomorrow')], default=0),
        ),
    ]
